### ISSUE TITLE
Remove the disconnection bar from palindrom-client

### ISSUE THREAD

**Issue by warpech** [Palindrom/palindrom-client#69]
The disconnection bar is not user friendly. We should hide the internal errors from the end users. Small steps towards that:

1. Move the disconnection bar into a custom element that can be used in a layout
2. Palindrom sends events. App shell listens to events and writes to `console.log`
3. Check if `console.log` can be read and `WebView` can be debugged in React Native apps
4. Solution owner can present disconnection message on screen by listening to these events

**Comment by alshakero** [comment]
> Check if console.log can be read and WebView can be debugged in React Native apps

It doesn't, I checked. However, using a normal browser instead of a WebView to debug works great so far.

**Comment by warpech** [comment]
Then again React Native stays behind "real native", because it's possible there:

- https://stackoverflow.com/questions/6508313/javascript-console-log-in-an-ios-uiwebview
- https://stackoverflow.com/questions/30291607/get-javascript-console-when-emulating-webview-app

**Comment by alshakero** [comment]
@tomalec and I agreed that:

1. We totally remove **reconnection** yellow bar. Because it simply indicates a glitch that the user cannot do anything about, and the app automatically recovers from it without any user action, it's only a source of annoyence. 

2. However, for debugging purposes, we log when Palindrom reconnects in console. And keep the all connection-related events like reconnection and disconnection.
3. We keep some UI for the unrecoverable failure state in a seperate custom elements that people can fork and stylize it the way they desire. In this custom element, we listen to all the events and either log a message or show some UI, or both. This will give users a clear idea how to handle events.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Palindrom/palindrom-client/pull/71
