### ISSUE TITLE
Notifying Polymer is slow with many array items

### ISSUE THREAD

**Issue by warpech** [Palindrom/palindrom-client#72]
@miyconst was contacted by @eriksunsol with a performance problem in appling Palindrom patches received by the client.

Erik has an array of 1500 objects. When he triggers server-side sorting of the data, the patch that is sent to the client contains 1500 operations of replacing the sorting number. Applying of this patch freezes the web browser for 3 minutes.

Erik has done some performance investigation and he has identified Polymer notification as the bottleneck.

We are benchmarking the performance of patch application (https://github.com/Starcounter/PalindromBenchmark), so it is surprising to me. We need to address it with high prio by providing a fix or a workaround.

One of the possible workarounds that I can think of is to unbind and bind Polymer again instead of notifying it. Of course, a fix is preferable to a workaround.
 
@alshakero could you please try to reproduce this problem? 

@miyconst, @eriksunsol - what is the Starcounter version that exhibits this problem?

**Comment by miyconst** [comment]
It is `2.3.1` or `2.3.2` as far as I know. @eriksunsol should know better.

**Comment by alshakero** [comment]
@miyconst so it's Polymer 1.x?

**Comment by alshakero** [comment]
Polymer seems to handle updates quite well.

Polymer 2.x: https://plnkr.co/edit/fJrj3gkh3IycjbC6MJOF?p=preview
Polymer 1.x: https://plnkr.co/edit/oQ9oxMKkcQz8UhUvWRUn?p=preview

**Comment by alshakero** [comment]
It just occurred to me that I should use notifySplices not notifyPath for a more accurate recreation of the issue. I’ll do that soon.

**Comment by alshakero** [comment]
Created new two for `notifySplices` and it is slower but still quite fast

Polymer 2.x: https://plnkr.co/edit/UJu3q4RfwgurNhnIgqru?p=preview
Polymer 1.x: https://plnkr.co/edit/mpe6VyNamJCgVyubTcnG?p=preview

Polymer 1.x is slower. But both didn't exceed 1 second for N = 10000;

I'm not sure if this is a Polymer issue anymore. And I would have suspected JSONPatcherProxy because it [had history with arrays](https://github.com/Palindrom/JSONPatcherProxy/issues/16) but as per the issue the data is being rearranged and diffed on the server. So it's either a fast-json-patch issue, OT issue, Palindrom issue, or a Polymer issue and my benchmark isn't good.

**Comment by miyconst** [comment]
@alshakero thank you for the investigation. Let's see if @eriksunsol could provide a reproduction scenario.

**Comment by warpech** [comment]
> Let's see if @eriksunsol could provide a reproduction scenario.

And the exact versions of Starcounter, Polymer and Palindrom (PuppetJs) if possible.

**Comment by eriksunsol** [comment]
Starcounter-RC-2.3.1.7877 with stock Palindrom, Palindrom-Client and to the best of my knowledge we're running Polymer 1.7.1.

I think we have a few different patch scenarios which all result in lots of time spent in Polymer notification propagation. As stated above we're talking about some 1500 operations in a single patch message. The one I looked at last is actually not a replace, but an add, where there is an array of 1500 elements, each element containing another smaller array, and each of those inner arrays get an additional element added.

I haven't looked at how Palindrom-Client executes notifications to Polymer, so there may be something we're not doing in an optimal way when e.g. binding parts of the view model to Polymer elements, but we do have lots of elements on the page and quite deep hierarchy of nested Polymer elements.

I ran profiling in the Chrome debugger (well, that's how I know most time is spent in Polymer notification processing), and the calls are really deep, which I suspect is coherent with the depth of the DOM with respect to nesting Polymer elements.

I may be able to provide an example screen-dump from the profiler, stack-trace, etc, later.

**Comment by alshakero** [comment]
If you could right click on the WebSocket frame under Network Tab in in Chrome DevTools and then click "copy", and put it here it would be the most helpful. If this is unclear I can prepate a GIF for you.

**Comment by eriksunsol** [comment]
I talked briefly to @miyconst about this, and I think I can do better: I'll prepare a real example for you to run on our dev server. I'll pass along credentials and a link on a separate channel. This will be tomorrow as that particular server is currently in maintenance mode...

**Comment by alshakero** [comment]
There is a decent chance that it will be waste of your effort. You'd probably help as much if you just give show me the patch frame. I'm not 100% sure though. I say it's worth a try before you spend a lot of time. I'll tell you in a few minutes if I could repro using only the patch.

**Comment by eriksunsol** [comment]
OK, though I think you'll want the page as well to fully grasp what's going on. I think I'll be able to prepare the example without much effort.

**Comment by warpech** [comment]
Ping @eriksunsol. 

I am removing it from the list of prioritized issues for the time being.

**Comment by eriksunsol** [comment]
Sorry for the delay. Other matters got in the way unfortunately.

Finally I have an example running. It would be preferable if I can show it to someone face to face, or if we can set up a conference call and share a screen I can guide you through it. Let me know if that's possible.

cc @warpech

**Comment by warpech** [comment]
@alshakero, @eriksunsol pls have a Hangout. I've hooked you up by email in case you don't have each others contact info.

**Comment by alshakero** [comment]
@eriksunsol and I Skyped today and he showed me the repro and gave me access to reproduce it too. There are login creds and this is a public repo, if anyone is interested in reproducing it please ping me on Slack.

There is 500KB patch being sent from the server, JSONPatcherProxy and Palindrom are not even visible in the performance audit results table (which is great), what appears and is taking all the time is `notifySplices` call in `palindrom-client`. 

My prognosis is that the DOM is being updated after every operation of this huge patch (3149 operations). Becasue we iterate over the patch and call `notifySplices` for every operation.

What I will be trying is calling `notifySplices` once, with the whole patch (as opposed to multiple times for individual operations). All this relies on the hope that Polymer is smart enough to only touch the DOM once if I pass all the patch to it. I'll update the issue once I know.

If polymer isn't that smart, I'll expirement with replacing the whole array at once. Instead of updating its children. But I certainly like the first solution more.

**Comment by alshakero** [comment]
Update:

I investigated the issue and tried several strategies, most promising are:

1. Replace the whole array instead of actually notifying it several times. This didn't yield any performance improvement. Because what's happenning is that the app is doing  thousands of updates to thousands of smaller arrays. Replacing the whole 4-element array or notifying Polymer about updating an element within it didn't make a difference. Because it's still happening thousands of times.

2. Resetting the whole view-model instead of bothering about notifying thousands of child leaf-node arrays. This is the most plausible solution so far. But due to Polymer 1 asynchronousity it isn't working. Setting the same model again means nothing. i.e: `this.set('model', this.model)` doesn't actually update the DOM, because  when Polymer diffs it sees `this.model === this.model` and doesn't do anything. To bump Polymer you need to do 
```js
const oldModel = this.get('model');
this.set('model', {});
this.set('model', oldModel )
```
But consecutive sync updates cause issues on Polymer. They're batched in a way and for them to work you need:
```
this.set('model', {});
setTimeout(() => this.set('model', this.model));
```
For now, this breaks the app in a flood of race conditions and error messages. 

I'm now investigating making solution 2 work. It should eventually work because it is already working to render a given view model when you first visit the app. Why wouldn't it be doable during runtime?
